### ISSUE TITLE
Option to re-position attributions

### ISSUE THREAD

**Issue by kamerat** [Norkart/L.TileLayer.Webatlas#3]
### When using this package, I cannot seem to change the attributions positioning

I assume you are doing this to stop people from removing the attributions? Either way, It would be nice to be able to re-position this.

**Use-case:**
Some map-actions on the bottom-right side of the map

**What is happening:**
Custom bottom-right side actions are colliding with the attributions.

I believe this has to do with the way you re-initializing the attributions on each move event: [src/L.TileLayer.Webatlas.js#L92:L108](https://github.com/Norkart/L.TileLayer.Webatlas/blob/acd4fba82e4b1cff33d420d328968378ba3ade0b/src/L.TileLayer.Webatlas.js#L92:L108)
```JS
_onMapMoved: function (e) {
    //get copyright text for current viewport
    var text = this._getCopyrightText();

    //add an attribution control if the default is disabled
    if (!this._map.attributionControl)  {
        this._map.attributionControl = L.control.attribution().addTo(this._map);
    }
    //remove the previous attribution we set
    this._map.attributionControl.removeAttribution(this._attribution);

    //set the new attribution
    this._map.attributionControl.addAttribution(text);

    //store the current so that we can remove it later
    this._attribution = text;
},
```

Is it possible to add an option to position this like it is intended to, as seen in the default leaflet docs; [Control.Attribution](https://leafletjs.com/reference-1.7.1.html#control-attribution)

<details open>
<summary>
Options inherited from <a href="https://leafletjs.com/reference-1.7.1.html#control">Control</a>
</summary>

Option | Type | Default | Description
-- | -- | -- | --
position | String | 'topright' | The position of the control (one of the map corners). Possible values are 'topleft', 'topright', 'bottomleft' or 'bottomright'

</details>

**Comment by atlefren** [comment]
Thanks for pointing this out, should be fixed in 1.2.0, where you can set the attributionPosition-option
