### ISSUE TITLE
index.d.ts has no default export.

### ISSUE THREAD

**Issue by AndreasOlausson** [Norkart/L.TileLayer.Webatlas#7]
node_modules/leaflet-webatlastile/build/index.d.ts:1:8 - error TS1192: Module '"C:/.../node_modules/@types/leaflet/index"' has no default export.
 
import L from 'leaflet'; 
should be
import * as L from 'leaflet';

**Comment by atlefren** [comment]
Thanks for pointing this one out! Will investigate!

**Comment by atlefren** [comment]
Hmm, I tried re-creating your issue, but I cannot reproduce it. 


Try cloning this repo: https://github.com/atlefren/webatlas_tilelayer_example

and do: 
1. Edit index.js and add your api key
2. npm install -g parcel-bundler
3. npm i 
4. parcel index.html


This works fine for me.

Care to share a minimal example showing the issue?

**Comment by AndreasOlausson** [comment]
Thanks, your example works fine! But I think this is a problem with typescript.
I have an angular application (ng 12.1.4, ts 4.3.5)

I can build my solution if.

1. change index.d.ts (node_modules) to "import * as L from 'leaflet')
2. add @ts-ignore on the line above import L as 'leaflet'
3. add "allowSyntheticDefaultImports": true to my tsconfig.json (compilerOptions).

https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports


We can't use 1 & 2 for obvious reasons, it would be overridden on npm -i.

3 could be an option, I would rather see * as L but I can live with it!


Our way to initialize the map is like this:

map.component.ts:

```
initMap(): void {

   const leafletOptions: L.MapOptions = { ...options... }

   this.map = new L.Map('map', leafletOptions)

   this.mapService.onMapReady(this.map);
```

mapService.ts

```
  onMapReady(map: Map): void {

        this.mapTypes = new MapTypes(map);

    }
```

webatlas-map-types:

```
import { IMapType } from "@models/map.model";
import { Map } from "leaflet";
import * as L from "leaflet";
import "leaflet-webatlastile";

export class MapTypes {
    private tileTypes: IMapType[] = [];
    selectedMapType: IMapType = null;
    private map: L.Map;

    constructor(map: Map) {
        this.map = map;
        const apiKey = "xxxxxxxxxxxxxxxxxxxxxxx";
        this.tileTypes.push(
            {
                name: "vectorTiles",
                description: "Terreng",
                layer: (L.tileLayer as any).webatlas({
                    mapType: (L.TileLayer  as any).Webatlas.Type.VECTOR,
                    apikey: apiKey
                })
            });
        this.tileTypes.push(
            {
                name: "greyTiles",
                description: "Terreng, svart/hvitt",
                layer: (L.tileLayer as any).webatlas({
                    mapType: (L.TileLayer as any).Webatlas.Type.GREY,
                    apikey: apiKey
                })
            });
        this.tileTypes.push(
            {
                name: "photoTiles",
                description: "Foto",
                layer: (L.tileLayer as any).webatlas({
                    mapType: (L.TileLayer as any).Webatlas.Type.AERIAL,
                    apikey: apiKey
                })
            });
        this.tileTypes.push(
            {
                name: "hybridTiles",
                description: "Hybrid",
                layer: (L.tileLayer as any).webatlas({
                    mapType: (L.TileLayer as any).Webatlas.Type.HYBRID,
                    apikey: apiKey
                })
            });
        this.setSelectedMapType(this.tileTypes[0]);
    }
    setSelectedMapType(mapType: IMapType) {
        if (this.selectedMapType != null) {
            this.map.removeLayer(this.selectedMapType.layer);
        }
        this.selectedMapType = mapType;
        this.map.addLayer(this.selectedMapType.layer);
    }
    getActiveTypeName(): string {
        if (this.selectedMapType != null) {
            return this.selectedMapType.name;
        }
        return null;
    }
    getAllTypes(): IMapType[] {
        return this.tileTypes;
    }
}
```

**Comment by atlefren** [comment]
Ah, I see, I assumed there was an error with the js version, as I've tested this with typescript and it worked fine here.

I assume that 

3. add "allowSyntheticDefaultImports": true to my tsconfig.json (compilerOptions). 

is the easiest way forward, so if you can live with that option that would be the easiest thing. However, I see your point, and will try to investigate if this requirement can be dropped (and at least document it properly)

**Comment by AndreasOlausson** [comment]
Yeah, I thought that to because to compiler pointed out index.d.ts as the bad boy.

I'll go with my third option!

Thank you for quick support!
